// Levels normalized from Tone.js time notation to plain beat values.
// duration and startBeat are in quarter-note beats (1 = quarter note, 0.5 = eighth, etc.)

const levels = [
  {
    id: "level-1",
    levelNumber: 1,
    title: "Brother John",
    composer: "Traditional",
    image: "./images/brotherjohn.jpg",
    bpm: 140,
    difficulty: 1,
    timeLimitSeconds: 200,
    description: [
      "Frère Jacques (in the nursery rhyme and in song more generally), also known in English as Brother John, is a nursery rhyme of French origin. The rhyme is traditionally sung in a round. The song is about a friar who has overslept and is urged to wake up and sound the bell for the matins.",
      "This is an easy piece to warm up and introduce you to the game!",
      "Make sure to sing along!",
    ],
    successText: "Well Done! Brother John is now awake... You pass to the next level",
    piece: [
      { pitch: "C4", duration: 1, startBeat: 0 },
      { pitch: "D4", duration: 1, startBeat: 1 },
      { pitch: "E4", duration: 1, startBeat: 2 },
      { pitch: "C4", duration: 1, startBeat: 3 },
      { pitch: "C4", duration: 1, startBeat: 4 },
      { pitch: "D4", duration: 1, startBeat: 5 },
      { pitch: "E4", duration: 1, startBeat: 6 },
      { pitch: "C4", duration: 1, startBeat: 7 },
      { pitch: "E4", duration: 1, startBeat: 8 },
      { pitch: "F4", duration: 1, startBeat: 9 },
      { pitch: "G4", duration: 2, startBeat: 10 },
    ],
  },
  {
    id: "level-2",
    levelNumber: 2,
    title: "The Legend of Zelda",
    composer: "Koji Kondo",
    image: "./images/zelda.jpg",
    bpm: 140,
    difficulty: 2,
    timeLimitSeconds: 200,
    description: [
      "The Legend of Zelda is a fantasy action-adventure video game franchise created by Japanese game designers Shigeru Miyamoto and Takashi Tezuka.",
      "Here we play the main theme from the original NES version!!",
      "Enjoy!!",
    ],
    successText: "PRINCESS SAVED!! LET'S MOVE ON TO THE NEXT LEVEL",
    piece: [
      { pitch: "A4",  duration: 1,    startBeat: 0 },
      { pitch: "E4",  duration: 1.5,  startBeat: 1 },
      { pitch: "A4",  duration: 1,    startBeat: 2.5 },
      { pitch: "A4",  duration: 0.25, startBeat: 3.5 },
      { pitch: "B4",  duration: 0.25, startBeat: 3.75 },
      { pitch: "C#5", duration: 0.25, startBeat: 4 },
      { pitch: "D5",  duration: 0.25, startBeat: 4.25 },
      { pitch: "E5",  duration: 2,    startBeat: 4.5 },
      { pitch: "E5",  duration: 2,    startBeat: 7 },
      { pitch: "E5",  duration: 0.33, startBeat: 9 },
      { pitch: "F5",  duration: 0.33, startBeat: 9.33 },
      { pitch: "G5",  duration: 0.33, startBeat: 9.66 },
      { pitch: "A5",  duration: 1.5,  startBeat: 10 },
      { pitch: "A5",  duration: 0.5,  startBeat: 11.5 },
      { pitch: "A5",  duration: 0.33, startBeat: 12 },
      { pitch: "G5",  duration: 0.33, startBeat: 12.33 },
      { pitch: "F5",  duration: 0.33, startBeat: 12.66 },
      { pitch: "G5",  duration: 0.75, startBeat: 13 },
      { pitch: "F5",  duration: 0.25, startBeat: 13.75 },
      { pitch: "E5",  duration: 2,    startBeat: 14 },
    ],
  },
  {
    id: "level-3",
    levelNumber: 3,
    title: "Bach to Bach",
    composer: "Johann Sebastian Bach",
    image: "./images/bach.jpg",
    bpm: 140,
    difficulty: 3,
    timeLimitSeconds: 200,
    description: [
      "Johann Sebastian Bach (31 March 1685 – 28 July 1750) was a German composer and musician of the Baroque period. He is known for instrumental compositions such as the Art of Fugue, the Brandenburg Concertos, and the Goldberg Variations.",
      "This piece is the well-known first prelude in C Major for the Well-tempered clavier. An absolute classic that everyone loves to listen to.",
      "You only have to play the first bar here! Have fun!",
    ],
    successText: "LEVEL PASSED!!! YOU ARE A MASTER OF BAROQUE MUSIC",
    piece: [
      { pitch: "C4", duration: 0.25, startBeat: 0 },
      { pitch: "E4", duration: 0.25, startBeat: 0.25 },
      { pitch: "G4", duration: 0.25, startBeat: 0.5 },
      { pitch: "C5", duration: 0.25, startBeat: 0.75 },
      { pitch: "E5", duration: 0.25, startBeat: 1 },
      { pitch: "G4", duration: 0.25, startBeat: 1.25 },
      { pitch: "C5", duration: 0.25, startBeat: 1.5 },
      { pitch: "E5", duration: 0.25, startBeat: 1.75 },
      { pitch: "C4", duration: 0.25, startBeat: 2 },
      { pitch: "E4", duration: 0.25, startBeat: 2.25 },
      { pitch: "G4", duration: 0.25, startBeat: 2.5 },
      { pitch: "C5", duration: 0.25, startBeat: 2.75 },
      { pitch: "E5", duration: 0.25, startBeat: 3 },
      { pitch: "G4", duration: 0.25, startBeat: 3.25 },
      { pitch: "C5", duration: 0.25, startBeat: 3.5 },
      { pitch: "E5", duration: 0.25, startBeat: 3.75 },
      { pitch: "C4", duration: 0.25, startBeat: 4 },
      { pitch: "D4", duration: 0.25, startBeat: 4.25 },
      { pitch: "A4", duration: 0.25, startBeat: 4.5 },
      { pitch: "D5", duration: 0.25, startBeat: 4.75 },
      { pitch: "F5", duration: 0.25, startBeat: 5 },
      { pitch: "A4", duration: 0.25, startBeat: 5.25 },
      { pitch: "D5", duration: 0.25, startBeat: 5.5 },
      { pitch: "F5", duration: 0.25, startBeat: 5.75 },
      { pitch: "C4", duration: 0.25, startBeat: 6 },
      { pitch: "D4", duration: 0.25, startBeat: 6.25 },
      { pitch: "A4", duration: 0.25, startBeat: 6.5 },
      { pitch: "D5", duration: 0.25, startBeat: 6.75 },
      { pitch: "F5", duration: 0.25, startBeat: 7 },
      { pitch: "A4", duration: 0.25, startBeat: 7.25 },
      { pitch: "D5", duration: 0.25, startBeat: 7.5 },
      { pitch: "F5", duration: 0.25, startBeat: 7.75 },
    ],
  },
  {
    id: "level-4",
    levelNumber: 4,
    title: "The Beatles",
    composer: "George Harrison",
    image: "./images/beatles.jpg",
    bpm: 140,
    difficulty: 3,
    timeLimitSeconds: 200,
    description: [
      "The Beatles were an English rock band formed in Liverpool in 1960. The line-up of John Lennon, Paul McCartney, George Harrison and Ringo Starr led the band to be regarded as the foremost and most influential in history.",
      "Here Comes the Sun is a song written by George Harrison, first released on the Beatles' 1969 album Abbey Road.",
      "Have fun playing this iconic song!!!",
    ],
    successText: "YOU MADE THE SUN SHINE TODAY - WELCOME TO LEVEL 5!!",
    // Original used 0.7 * eighth-note subdivisions — preserved as fractional beats
    piece: [
      { pitch: "C#5", duration: 0.35, startBeat: 0 },
      { pitch: "A4",  duration: 0.35, startBeat: 0.35 },
      { pitch: "B4",  duration: 0.35, startBeat: 0.7 },
      { pitch: "C#5", duration: 0.7,  startBeat: 1.05 },
      { pitch: "A4",  duration: 1.05, startBeat: 1.75 },
      { pitch: "C#5", duration: 0.35, startBeat: 2.8 },
      { pitch: "B4",  duration: 0.7,  startBeat: 3.15 },
      { pitch: "A4",  duration: 0.49, startBeat: 3.85 },
      { pitch: "F#4", duration: 1.05, startBeat: 4.55 },
      { pitch: "A4",  duration: 0.7,  startBeat: 5.6 },
      { pitch: "B4",  duration: 0.7,  startBeat: 6.3 },
      { pitch: "A4",  duration: 0.49, startBeat: 7 },
      { pitch: "F#4", duration: 0.35, startBeat: 7.7 },
      { pitch: "G#4", duration: 0.35, startBeat: 8.05 },
      { pitch: "F#4", duration: 0.35, startBeat: 8.4 },
      { pitch: "G#4", duration: 0.35, startBeat: 8.75 },
      { pitch: "A4",  duration: 0.49, startBeat: 9.1 },
      { pitch: "B4",  duration: 0.875, startBeat: 9.8 },
      { pitch: "C#5", duration: 0.35, startBeat: 11.55 },
      { pitch: "A4",  duration: 0.35, startBeat: 11.9 },
      { pitch: "B4",  duration: 0.35, startBeat: 12.25 },
      { pitch: "C#5", duration: 0.7,  startBeat: 12.6 },
      { pitch: "A4",  duration: 1.05, startBeat: 13.3 },
      { pitch: "C#5", duration: 0.35, startBeat: 14.35 },
      { pitch: "B4",  duration: 0.7,  startBeat: 14.7 },
      { pitch: "A4",  duration: 0.49, startBeat: 15.4 },
      { pitch: "F#4", duration: 1.05, startBeat: 16.1 },
      { pitch: "C#5", duration: 0.35, startBeat: 17.15 },
      { pitch: "B4",  duration: 0.7,  startBeat: 17.5 },
      { pitch: "A4",  duration: 0.49, startBeat: 18.2 },
      { pitch: "G#4", duration: 1.75, startBeat: 18.9 },
    ],
  },
  {
    id: "level-5",
    levelNumber: 5,
    title: "Queen",
    composer: "Freddie Mercury",
    image: "./images/queen.jpg",
    bpm: 140,
    difficulty: 4,
    timeLimitSeconds: 300,
    description: [
      "Queen are a British rock band formed in London in 1970. Their classic line-up was Freddie Mercury, Brian May, Roger Taylor and John Deacon.",
      "Although critical reaction was initially mixed, 'Bohemian Rhapsody' became Queen's most popular song and is considered one of the greatest rock songs.",
      "After playing it you should be ready to go on stage!!!",
    ],
    successText: "LEVEL PASSED. YOU ROOOOCK, MEET YOU IN WEMBLEY",
    piece: [
      { pitch: "D4",  duration: 0.65, startBeat: 0 },
      { pitch: "F3",  duration: 0.65, startBeat: 0.65 },
      { pitch: "A#3", duration: 0.65, startBeat: 1.3 },
      { pitch: "D4",  duration: 0.65, startBeat: 1.95 },
      { pitch: "G4",  duration: 0.65, startBeat: 2.6 },
      { pitch: "F3",  duration: 0.65, startBeat: 3.25 },
      { pitch: "F4",  duration: 0.65, startBeat: 3.9 },
      { pitch: "F3",  duration: 0.65, startBeat: 4.55 },
      { pitch: "D4",  duration: 0.65, startBeat: 5.2 },
      { pitch: "F3",  duration: 0.65, startBeat: 5.85 },
      { pitch: "A#3", duration: 0.65, startBeat: 6.5 },
      { pitch: "D4",  duration: 0.65, startBeat: 7.15 },
      { pitch: "G4",  duration: 0.65, startBeat: 7.8 },
      { pitch: "F3",  duration: 0.65, startBeat: 8.45 },
      { pitch: "F4",  duration: 0.65, startBeat: 9.1 },
      { pitch: "F3",  duration: 0.65, startBeat: 9.75 },
      { pitch: "D4",  duration: 0.65, startBeat: 10.4 },
      { pitch: "G3",  duration: 0.65, startBeat: 11.05 },
      { pitch: "A#3", duration: 0.65, startBeat: 11.7 },
      { pitch: "D4",  duration: 0.65, startBeat: 12.35 },
      { pitch: "A4",  duration: 0.65, startBeat: 13 },
      { pitch: "G3",  duration: 0.65, startBeat: 13.65 },
      { pitch: "G4",  duration: 0.65, startBeat: 14.3 },
      { pitch: "G3",  duration: 0.65, startBeat: 14.95 },
      { pitch: "D#4", duration: 0.65, startBeat: 15.6 },
      { pitch: "C4",  duration: 0.65, startBeat: 16.25 },
      { pitch: "D#4", duration: 0.65, startBeat: 16.9 },
      { pitch: "G4",  duration: 0.65, startBeat: 17.55 },
      { pitch: "D5",  duration: 0.65, startBeat: 18.2 },
      { pitch: "C4",  duration: 0.65, startBeat: 18.85 },
      { pitch: "C5",  duration: 0.65, startBeat: 19.5 },
      { pitch: "C4",  duration: 0.65, startBeat: 20.15 },
      { pitch: "A#4", duration: 0.65, startBeat: 20.8 },
      { pitch: "C4",  duration: 0.65, startBeat: 21.45 },
      { pitch: "D#4", duration: 0.65, startBeat: 22.1 },
      { pitch: "G4",  duration: 0.65, startBeat: 22.75 },
      { pitch: "A4",  duration: 0.65, startBeat: 23.4 },
      { pitch: "D#4", duration: 0.65, startBeat: 24.05 },
      { pitch: "F4",  duration: 0.65, startBeat: 24.7 },
      { pitch: "C5",  duration: 0.65, startBeat: 25.35 },
      { pitch: "D4",  duration: 0.65, startBeat: 26 },
      { pitch: "F3",  duration: 0.65, startBeat: 26.65 },
      { pitch: "A#3", duration: 0.65, startBeat: 27.3 },
      { pitch: "D4",  duration: 0.65, startBeat: 27.95 },
      { pitch: "G4",  duration: 0.65, startBeat: 28.6 },
      { pitch: "F3",  duration: 0.65, startBeat: 29.25 },
      { pitch: "F4",  duration: 0.65, startBeat: 29.9 },
      { pitch: "F3",  duration: 0.65, startBeat: 30.55 },
    ],
  },
];

module.exports = { levels };
